pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/hariharan346/mern-deployment.git', branch: 'main'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t mern-backend ./backend'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t mern-frontend .'
            }
        }
    }
}
