pipeline {
    agent any

    environment {
        DOCKER_HUB = "godparticle"
    }

    stages {

        stage('Build Backend Image') {
            steps {
                dir('without-admin-/backend') {
                    sh 'docker build -t $DOCKER_HUB/mern-backend .'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('without-admin-') {
                    sh 'docker build -t $DOCKER_HUB/mern-frontend .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                sh 'docker push $DOCKER_HUB/mern-backend'
            }
        }

        stage('Push Frontend Image') {
            steps {
                sh 'docker push $DOCKER_HUB/mern-frontend'
            }
        }
    }
}