pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/hariharan346/mern-deployment.git', branch: 'main'
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('without-admin-/backend') {
                    sh 'docker build -t mern-backend .'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('without-admin-') {
                    sh 'docker build -t mern-frontend .'
                }
            }
        }
    }
}
